spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}/postgres
    username: postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: create-drop
